"""add created_at and update_at

Revision ID: b2a7b152e094
Revises: f136b5201fe6
Create Date: 2024-04-01 00:54:44.883282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a7b152e094'
down_revision: Union[str, None] = 'f136b5201fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('Task', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('Users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('Users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'updated_at')
    op.drop_column('Users', 'created_at')
    op.drop_column('Task', 'updated_at')
    op.drop_column('Task', 'created_at')
    # ### end Alembic commands ###
